version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build: 
  commands:
   - sam build
   - export BUCKET=python-trivia-party
   - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
 type: zip
 files:
  - template.yaml
  - outputtemplate.yaml